# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_clean.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common_clean.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon_clean.proto\x12\"v2ray.core.app.router.routercommon\"\xab\x02\n\x06\x44omain\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.v2ray.core.app.router.routercommon.Domain.Type\x12\r\n\x05value\x18\x02 \x01(\t\x12G\n\tattribute\x18\x03 \x03(\x0b\x32\x34.v2ray.core.app.router.routercommon.Domain.Attribute\x1aR\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x42\r\n\x0btyped_value\"6\n\x04Type\x12\t\n\x05Plain\x10\x00\x12\t\n\x05Regex\x10\x01\x12\x0e\n\nRootDomain\x10\x02\x12\x08\n\x04\x46ull\x10\x03\"\"\n\x04\x43IDR\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0e\n\x06prefix\x18\x02 \x01(\r\"\x91\x01\n\x05GeoIP\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x36\n\x04\x63idr\x18\x02 \x03(\x0b\x32(.v2ray.core.app.router.routercommon.CIDR\x12\x15\n\rinverse_match\x18\x03 \x01(\x08\x12\x15\n\rresource_hash\x18\x04 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x05 \x01(\t\"E\n\tGeoIPList\x12\x38\n\x05\x65ntry\x18\x01 \x03(\x0b\x32).v2ray.core.app.router.routercommon.GeoIP\"\x80\x01\n\x07GeoSite\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12:\n\x06\x64omain\x18\x02 \x03(\x0b\x32*.v2ray.core.app.router.routercommon.Domain\x12\x15\n\rresource_hash\x18\x03 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\"I\n\x0bGeoSiteList\x12:\n\x05\x65ntry\x18\x01 \x03(\x0b\x32+.v2ray.core.app.router.routercommon.GeoSiteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_clean_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOMAIN']._serialized_start=59
  _globals['_DOMAIN']._serialized_end=358
  _globals['_DOMAIN_ATTRIBUTE']._serialized_start=220
  _globals['_DOMAIN_ATTRIBUTE']._serialized_end=302
  _globals['_DOMAIN_TYPE']._serialized_start=304
  _globals['_DOMAIN_TYPE']._serialized_end=358
  _globals['_CIDR']._serialized_start=360
  _globals['_CIDR']._serialized_end=394
  _globals['_GEOIP']._serialized_start=397
  _globals['_GEOIP']._serialized_end=542
  _globals['_GEOIPLIST']._serialized_start=544
  _globals['_GEOIPLIST']._serialized_end=613
  _globals['_GEOSITE']._serialized_start=616
  _globals['_GEOSITE']._serialized_end=744
  _globals['_GEOSITELIST']._serialized_start=746
  _globals['_GEOSITELIST']._serialized_end=819
# @@protoc_insertion_point(module_scope)
